# -*- coding: utf-8 -*-
"""random forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140TzsEwlgIAChutgAwwLh3mTh3Y6nJqx
"""

import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

df=pd.read_csv("/content/sample_data/Cancer_Data.csv")

df

df.isnull().sum()

df['area_se'].median()

df['area_se']

df.shape

df.describe()

df.describe().T

df.tail()

df['id'].unique()

df['id'].mode()

df.duplicated()

df.info()

df.tail()

df.describe()

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.drop('diagnosis',axis=1),df['diagnosis'],test_size=0.3,random_state=1)

X_test.shape

X_train.shape

X.shape

X_test.shape

y.shape

df.boxplot(column='area_se', by='diagnosis')
plt.title('Boxplot of area_se by Diagnosis')
plt.suptitle('') # Suppress the default suptitle
plt.show()

df.info()

df['diagnosis'].unique()

df['diagnosis'].value_counts()

df.info()

df.tail()

df.describe()

df.tail()

df.info()

df.isnull().sum()

df.tail()

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)*100

print(f"Accuracy of the Random Forest Classifier: {accuracy}")

